DROP TABLE IF EXISTS CSLIVE.INCR_CS_STG_ARTICLERELATION;

DROP TABLE IF EXISTS CSLIVE.INCR_CS_STG_COMPATIBILITIES;

DROP TABLE IF EXISTS CSLIVE.INCR_CS_STG_ARTICLE;

DROP TABLE IF EXISTS CSLIVE.INCR_CS_STG_ATTRIBUTE;

DROP TABLE IF EXISTS INCR_CS_STG_ATTRIBUTE_VALUE;

DROP TABLE IF EXISTS CSLIVE.INCR_CS_STG_MANUFACTURERS;

DROP TABLE IF EXISTS CSLIVE.INCR_CS_STG_REFERENCE;

DROP TABLE IF EXISTS CSLIVE.STG_BRIDGE_ARTCLREL_ATTRIBUTE;

DROP TABLE IF EXISTS CSLIVE.STG_BRIDGE_COMPATIBILITIES_ATTRIBUTE;

DROP TABLE IF EXISTS CSLIVE.STG_BRIDGE_ARTCTL_ATTRIBUTE;

DROP TABLE IF EXISTS CSLIVE.STG_BRIDGE_ARTCTL_COMPATIBILITIES;

DROP TABLE IF EXISTS CSLIVE.STG_BRIDGE_ARTCTL_MNUFCTRE;

DROP TABLE IF EXISTS CSLIVE.STG_BRIDGE_ARTCTL_REFRNCE;

DROP TABLE IF EXISTS CSLIVE.STG_BRIDGE_ATTRIBUTES;

DROP TABLE IF EXISTS CSLIVE.STG_BRIDGE_ENTITY;

DROP TABLE IF EXISTS CSLIVE.STG_BRIDGE_MANFCTR_ATTRIBUTE;

DROP TABLE IF EXISTS STG_BRIDGE_MNUFCTRE_REFRNCE;

DROP TABLE IF EXISTS CSLIVE.STG_BRIDGE_REFERENCE_ATTRIBUTE;

/*==============================================================*/
/* Table: INCR_CS_STG_ARTICLERELATION                           */
/*==============================================================*/
CREATE TABLE CSLIVE.INCR_CS_STG_ARTICLERELATION
(
   ARTICLERELATION_ID   BIGINT(20) NOT NULL AUTO_INCREMENT,
   ARCTL_PRODUCTID      VARCHAR(255) COLLATE utf8_unicode_ci NOT NULL,
   REL_ARCTL_PRODUCTID  VARCHAR(255) COLLATE utf8_unicode_ci NOT NULL,
   ARTICLE_LABEL        VARCHAR(60) COLLATE utf8_unicode_ci,
   RELARTICLE_LABEL     VARCHAR(60) COLLATE utf8_unicode_ci,
   EXTERNALKEY          VARCHAR(255) COLLATE utf8_unicode_ci,
   CREATIONDATE         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   CLIENT_ID            BIGINT(20),
   TRANS_ID             BIGINT(20),
   PRIMARY KEY (ARTICLERELATION_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

/*==============================================================*/
/* Table: INCR_CS_STG_COMPATIBILITIES                           */
/*==============================================================*/
CREATE TABLE CSLIVE.INCR_CS_STG_COMPATIBILITIES
(
   COMPTBL_SURROGATE_KEY BIGINT(20) NOT NULL AUTO_INCREMENT, 
   TYPE_ID              BIGINT(20),
   LANGUAGE          	VARCHAR(60) COLLATE utf8_unicode_ci NOT NULL,
   PRODUCT_ID           BIGINT(20),
   EXTERNALKEY          VARCHAR(255) COLLATE utf8_unicode_ci,
   CREATIONDATE         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   CLIENT_ID            BIGINT(20),
   TRANS_ID             BIGINT(20),
   PRIMARY KEY (COMPTBL_SURROGATE_KEY)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

/*==============================================================*/
/* Table: INCR_CS_STG_ARTICLE                                   */
/*==============================================================*/
CREATE TABLE CSLIVE.INCR_CS_STG_ARTICLE
(
   ARCTL_SURROGATE_KEY   BIGINT(20) NOT NULL AUTO_INCREMENT,
   ARTICLE_LABEL        VARCHAR(120) COLLATE utf8_unicode_ci,
   PARENT_ARTICLE_LABEL VARCHAR(120) COLLATE utf8_unicode_ci,
   ARTICLE_LANGUAGE     VARCHAR(50) COLLATE utf8_unicode_ci,
   CREATIONDATE         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRODUCT_ID           BIGINT(20),
   EXTERNALKEY          VARCHAR(255) COLLATE utf8_unicode_ci,
   CLIENT_ID            BIGINT(20),
   TRANS_ID             BIGINT(20),
   PRIMARY KEY (ARCTL_SURROGATE_KEY)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

/*==============================================================*/
/* Index: CLIENT_ID                                             */
/*==============================================================*/
CREATE INDEX CLIENT_ID ON CSLIVE.INCR_CS_STG_ARTICLE
(
   CLIENT_ID
);

/*==============================================================*/
/* Index: TRANS_ID                                              */
/*==============================================================*/
CREATE INDEX TRANS_ID ON CSLIVE.INCR_CS_STG_ARTICLE
(
   TRANS_ID
);

/*==============================================================*/
/* Table: INCR_CS_STG_ATTRIBUTE                                 */
/*==============================================================*/
CREATE TABLE CSLIVE.INCR_CS_STG_ATTRIBUTE
(
   ATTR_SURROGATE_KEY   BIGINT(20) NOT NULL AUTO_INCREMENT,
   EXTERNALKEY          VARCHAR(255) COLLATE utf8_unicode_ci,
   ATTRIBUTE_LABEL      VARCHAR(120) COLLATE utf8_unicode_ci NOT NULL,
   ATTRIBUTE_LANGUAGE   VARCHAR(50) COLLATE utf8_unicode_ci,
   CREATIONDATE         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   ENTITY_TYPE			int(11),
   CLIENT_ID            BIGINT(20),
   TRANS_ID             BIGINT(20),
   PRIMARY KEY (ATTR_SURROGATE_KEY)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

/*==============================================================*/
/* Index: CLIENT_ID                                             */
/*==============================================================*/
CREATE INDEX CLIENT_ID ON CSLIVE.INCR_CS_STG_ATTRIBUTE
(
   CLIENT_ID
);

/*==============================================================*/
/* Index: TRANS_ID                                              */
/*==============================================================*/
CREATE INDEX TRANS_ID ON CSLIVE.INCR_CS_STG_ATTRIBUTE
(
   TRANS_ID
);

/*==============================================================*/
/* Table: INCR_CS_STG_ATTRIBUTE_VALUE                           */
/*==============================================================*/
CREATE TABLE INCR_CS_STG_ATTRIBUTE_VALUE
(
   ATTR_SURROGATE_VALUE_KEY BIGINT(20) NOT NULL AUTO_INCREMENT,
   EXTERNALKEY          VARCHAR(255) COLLATE utf8_unicode_ci NOT NULL,
   ATTRIBUTE_VALUE      VARCHAR(2000) COLLATE utf8_unicode_ci,
   ATTRIBUTE_VALUE_TYPE	varchar(1000) COLLATE utf8_unicode_ci,
   ATTRIBUTE_LANGUAGE   VARCHAR(50) COLLATE utf8_unicode_ci,
   CREATIONDATE         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   ENTITY_TYPE			int(11),
   CLIENT_ID            BIGINT(20),
   TRANS_ID             BIGINT(20),
   PRIMARY KEY (ATTR_SURROGATE_VALUE_KEY)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

/*==============================================================*/
/* Table: INCR_CS_STG_MANUFACTURERS                             */
/*==============================================================*/
CREATE TABLE CSLIVE.INCR_CS_STG_MANUFACTURERS
(
   MANFCTR_SURROGATE_KEY BIGINT(20) NOT NULL AUTO_INCREMENT,
   MANUFACTURE_LABEL    VARCHAR(120) COLLATE utf8_unicode_ci,
   PARENT_MANUFACTURE_LABEL VARCHAR(120) COLLATE utf8_unicode_ci,
   MANUFACTURE_LANGUAGE VARCHAR(50) COLLATE utf8_unicode_ci,
   MODEL_ID             VARCHAR(120) COLLATE utf8_unicode_ci,
   EXTERNALKEY          VARCHAR(255) COLLATE utf8_unicode_ci,
   CREATIONDATE         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   CLIENT_ID            BIGINT(20),
   TRANS_ID             BIGINT(20),
   PRIMARY KEY (MANFCTR_SURROGATE_KEY)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

/*==============================================================*/
/* Index: CLIENT_ID                                             */
/*==============================================================*/
CREATE INDEX CLIENT_ID ON CSLIVE.INCR_CS_STG_MANUFACTURERS
(
   CLIENT_ID
);

/*==============================================================*/
/* Index: TRANS_ID                                              */
/*==============================================================*/
CREATE INDEX TRANS_ID ON CSLIVE.INCR_CS_STG_MANUFACTURERS
(
   TRANS_ID
);

/*==============================================================*/
/* Table: INCR_CS_STG_REFERENCE                                 */
/*==============================================================*/
CREATE TABLE CSLIVE.INCR_CS_STG_REFERENCE
(
   REF_SURROGATE_KEY    BIGINT(20) NOT NULL AUTO_INCREMENT,
   REF_LABEL            VARCHAR(120) COLLATE utf8_unicode_ci,
   PARENT_REF_LABEL     VARCHAR(120) COLLATE utf8_unicode_ci,
   REF_LANGUAGE         VARCHAR(50) COLLATE utf8_unicode_ci,
   NOTES                VARCHAR(4000) COLLATE utf8_unicode_ci,
   PRODUCT_ID           BIGINT(20),
   EXTERNALKEY          VARCHAR(255) COLLATE utf8_unicode_ci,
   CREATIONDATE         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   CLIENT_ID            BIGINT(20),
   TRANS_ID             BIGINT(20),
   PRIMARY KEY (REF_SURROGATE_KEY)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

/*==============================================================*/
/* Index: CLIENT_ID                                             */
/*==============================================================*/
CREATE INDEX CLIENT_ID ON CSLIVE.INCR_CS_STG_REFERENCE
(
   CLIENT_ID
);

/*==============================================================*/
/* Index: TRANS_ID                                              */
/*==============================================================*/
CREATE INDEX TRANS_ID ON CSLIVE.INCR_CS_STG_REFERENCE
(
   TRANS_ID
);

/*==============================================================*/
/* Table: STG_BRIDGE_ARTCLREL_ATTRIBUTE                         */
/*==============================================================*/
CREATE TABLE CSLIVE.STG_BRIDGE_ARTCLREL_ATTRIBUTE
(
   STG_BRDGE_REL_ATTR_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
   ARTICLERELATION_ID   BIGINT(20) NOT NULL,
   ATTR_STG_BRIDGE_KEY  BIGINT(20) NOT NULL,
   CREATIONDATE         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   CLIENT_ID            BIGINT(20),
   TRANS_ID             BIGINT(20),
   PRIMARY KEY (STG_BRDGE_REL_ATTR_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

/*==============================================================*/
/* Table: STG_BRIDGE_COMPATIBILITIES_ATTRIBUTE                  */
/*==============================================================*/
CREATE TABLE CSLIVE.STG_BRIDGE_COMPATIBILITIES_ATTRIBUTE
(
   STG_BRDGE_COMPTB_ATTR_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
   COMPTBL_SURROGATE_KEY BIGINT(20) NOT NULL,
   ATTR_STG_BRIDGE_KEY  BIGINT(20) NOT NULL,
   CREATIONDATE         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   CLIENT_ID            BIGINT(20),
   TRANS_ID             BIGINT(20),
   PRIMARY KEY (STG_BRDGE_COMPTB_ATTR_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

/*==============================================================*/
/* Table: STG_BRIDGE_ARTCTL_ATTRIBUTE                           */
/*==============================================================*/
CREATE TABLE CSLIVE.STG_BRIDGE_ARTCTL_ATTRIBUTE
(
   STG_BRDGE_ARTCL_ATTR_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
   ARCTL_SURROGATE_KEY  BIGINT(20) NOT NULL,
   ATTR_STG_BRIDGE_KEY  BIGINT(20) NOT NULL,
   CREATIONDATE         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   CLIENT_ID            BIGINT(20),
   TRANS_ID             BIGINT(20),
   PRIMARY KEY (STG_BRDGE_ARTCL_ATTR_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

/*==============================================================*/
/* Table: STG_BRIDGE_ARTCTL_COMPATIBILITIES                     */
/*==============================================================*/
CREATE TABLE CSLIVE.STG_BRIDGE_ARTCTL_COMPATIBILITIES
(
   STG_BRDGE_ARTCL_COMPTB_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
   ARCTL_SURROGATE_KEY  BIGINT(20) NOT NULL,
   COMPTBL_SURROGATE_KEY BIGINT(20) NOT NULL,
   CREATIONDATE         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   CLIENT_ID            BIGINT(20),
   TRANS_ID             BIGINT(20),
   PRIMARY KEY (STG_BRDGE_ARTCL_COMPTB_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

/*==============================================================*/
/* Table: STG_BRIDGE_ARTCTL_MNUFCTRE                            */
/*==============================================================*/
CREATE TABLE CSLIVE.STG_BRIDGE_ARTCTL_MNUFCTRE
(
   STG_BRDGE_ARTCL_MANFCTR_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
   ARCTL_SURROGATE_KEY   BIGINT(20) NOT NULL,
   MANFCTR_SURROGATE_KEY BIGINT(20) NOT NULL,
   CREATIONDATE         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   CLIENT_ID            BIGINT(20),
   TRANS_ID             BIGINT(20),
   PRIMARY KEY (STG_BRDGE_ARTCL_MANFCTR_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

/*==============================================================*/
/* Table: STG_BRIDGE_ARTCTL_REFRNCE                             */
/*==============================================================*/
CREATE TABLE CSLIVE.STG_BRIDGE_ARTCTL_REFRNCE
(
   STG_BRDGE_ARTCL_REF_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
   ARCTL_SURROGATE_KEY   BIGINT(20) NOT NULL,
   REF_SURROGATE_KEY    BIGINT(20) NOT NULL,
   CREATIONDATE         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   CLIENT_ID            BIGINT(20),
   TRANS_ID             BIGINT(20),
   PRIMARY KEY (STG_BRDGE_ARTCL_REF_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

/*==============================================================*/
/* Table: STG_BRIDGE_ATTRIBUTES                                 */
/*==============================================================*/
CREATE TABLE CSLIVE.STG_BRIDGE_ATTRIBUTES
(
   ATTR_STG_BRIDGE_KEY  BIGINT(20) NOT NULL AUTO_INCREMENT,
   ATTR_SURROGATE_KEY    BIGINT(20) NOT NULL,
   ATTR_SURROGATE_VALUE_KEY BIGINT(20) NOT NULL,
   CREATIONDATE         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   CLIENT_ID            BIGINT(20),
   TRANS_ID             BIGINT(20),
   PRIMARY KEY (ATTR_STG_BRIDGE_KEY)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

/*==============================================================*/
/* Table: STG_BRIDGE_ENTITY                                     */
/*==============================================================*/
CREATE TABLE CSLIVE.STG_BRIDGE_ENTITY
(
   STG_BRDGE_ENTITY_ID  BIGINT(20) NOT NULL AUTO_INCREMENT,
   ARCTL_SURROGATE_KEY   BIGINT(20) NOT NULL,
   MANFCTR_SURROGATE_KEY BIGINT(20) NOT NULL,
   REF_SURROGATE_KEY    BIGINT(20) NOT NULL,
   ARTICLERELATION_ID   BIGINT(20) NOT NULL,
   COMPTBL_SURROGATE_KEY BIGINT(20) NOT NULL,
   CREATIONDATE         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   CLIENT_ID            BIGINT(20),
   TRANS_ID             BIGINT(20),
   PRIMARY KEY (STG_BRDGE_ENTITY_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

/*==============================================================*/
/* Table: STG_BRIDGE_MANFCTR_ATTRIBUTE                          */
/*==============================================================*/
CREATE TABLE CSLIVE.STG_BRIDGE_MANFCTR_ATTRIBUTE
(
   STG_BRDGE_MNFCTR_ATTR_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
   MANFCTR_SURROGATE_KEY  BIGINT(20) NOT NULL,
   ATTR_STG_BRIDGE_KEY  BIGINT(20) NOT NULL,
   CREATIONDATE         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   CLIENT_ID            BIGINT(20),
   TRANS_ID             BIGINT(20),
   PRIMARY KEY (STG_BRDGE_MNFCTR_ATTR_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

/*==============================================================*/
/* Table: STG_BRIDGE_MNUFCTRE_REFRNCE                           */
/*==============================================================*/
CREATE TABLE STG_BRIDGE_MNUFCTRE_REFRNCE
(
   STG_BRDGE_MNFCTR_REF_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
   MANFCTR_SURROGATE_KEY BIGINT(20) NOT NULL,
   REF_SURROGATE_KEY    BIGINT(20) NOT NULL,
   CREATIONDATE         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   CLIENT_ID            BIGINT(20),
   TRANS_ID             BIGINT(20),
   PRIMARY KEY (STG_BRDGE_MNFCTR_REF_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

/*==============================================================*/
/* Table: STG_BRIDGE_REFERENCE_ATTRIBUTE                        */
/*==============================================================*/
CREATE TABLE CSLIVE.STG_BRIDGE_REFERENCE_ATTRIBUTE
(
   STG_BRDGE_REF_ATTR_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
   REF_SURROGATE_KEY     BIGINT(20) NOT NULL,
   ATTR_STG_BRIDGE_KEY  BIGINT(20) NOT NULL,
   CREATIONDATE         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   CLIENT_ID            BIGINT(20),
   TRANS_ID             BIGINT(20),
   PRIMARY KEY (STG_BRDGE_REF_ATTR_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

ALTER TABLE CSLIVE.INCR_CS_STG_ARTICLERELATION ADD CONSTRAINT FK_REFERENCE_39 FOREIGN KEY (REL_ARCTL_PRODUCTID)
      REFERENCES CSLIVE.INCR_CS_STG_ARTICLE (PRODUCT_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CSLIVE.INCR_CS_STG_ARTICLE ADD CONSTRAINT FK_REFERENCE_18 FOREIGN KEY ()
      REFERENCES CSLIVE.STG_BRIDGE_ENTITY (STG_BRDGE_ENTITY_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CSLIVE.INCR_CS_STG_ATTRIBUTE ADD CONSTRAINT FK_REFERENCE_29 FOREIGN KEY ()
      REFERENCES CSLIVE.INCR_CS_STG_ARTICLE (ARCTL_SURROGATE_KEY) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CSLIVE.INCR_CS_STG_ATTRIBUTE ADD CONSTRAINT FK_REFERENCE_30 FOREIGN KEY ()
      REFERENCES CSLIVE.INCR_CS_STG_MANUFACTURERS (MANFCTR_SURROGATE_KEY) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CSLIVE.INCR_CS_STG_ATTRIBUTE ADD CONSTRAINT FK_REFERENCE_31 FOREIGN KEY ()
      REFERENCES CSLIVE.INCR_CS_STG_REFERENCE (REF_SURROGATE_KEY) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CSLIVE.STG_BRIDGE_ARTCLREL_ATTRIBUTE ADD CONSTRAINT FK_REFERENCE_21 FOREIGN KEY (ARTICLERELATION_ID)
      REFERENCES CSLIVE.INCR_CS_STG_ARTICLERELATION (ARTICLERELATION_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CSLIVE.STG_BRIDGE_ARTCLREL_ATTRIBUTE ADD CONSTRAINT FK_REFERENCE_47 FOREIGN KEY (ATTR_STG_BRIDGE_KEY)
      REFERENCES CSLIVE.STG_BRIDGE_ATTRIBUTES (ATTR_STG_BRIDGE_KEY) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CSLIVE.STG_BRIDGE_COMPATIBILITIES_ATTRIBUTE ADD CONSTRAINT FK_REFERENCE_40 FOREIGN KEY (ATTR_STG_BRIDGE_KEY)
      REFERENCES CSLIVE.STG_BRIDGE_ATTRIBUTES (ATTR_STG_BRIDGE_KEY) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CSLIVE.STG_BRIDGE_COMPATIBILITIES_ATTRIBUTE ADD CONSTRAINT FK_REFERENCE_41 FOREIGN KEY (COMPTBL_SURROGATE_KEY)
      REFERENCES CSLIVE.INCR_CS_STG_COMPATIBILITIES (COMPTBL_SURROGATE_KEY) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CSLIVE.STG_BRIDGE_ARTCTL_ATTRIBUTE ADD CONSTRAINT FK_REFERENCE_33 FOREIGN KEY (ATTR_STG_BRIDGE_KEY)
      REFERENCES CSLIVE.STG_BRIDGE_ATTRIBUTES (ATTR_STG_BRIDGE_KEY) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CSLIVE.STG_BRIDGE_ARTCTL_ATTRIBUTE ADD CONSTRAINT FK_REFERENCE_34 FOREIGN KEY (ARCTL_SURROGATE_KEY)
      REFERENCES CSLIVE.INCR_CS_STG_ARTICLE (ARCTL_SURROGATE_KEY) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CSLIVE.STG_BRIDGE_ARTCTL_COMPATIBILITIES ADD CONSTRAINT FK_REFERENCE_42 FOREIGN KEY (ARCTL_SURROGATE_KEY)
      REFERENCES CSLIVE.INCR_CS_STG_ARTICLE (ARCTL_SURROGATE_KEY) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CSLIVE.STG_BRIDGE_ARTCTL_COMPATIBILITIES ADD CONSTRAINT FK_REFERENCE_43 FOREIGN KEY (COMPTBL_SURROGATE_KEY)
      REFERENCES CSLIVE.INCR_CS_STG_COMPATIBILITIES (COMPTBL_SURROGATE_KEY) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CSLIVE.STG_BRIDGE_ARTCTL_MNUFCTRE ADD CONSTRAINT FK_REFERENCE_24 FOREIGN KEY (ARCTL_SURROGATE_KEY)
      REFERENCES CSLIVE.INCR_CS_STG_ARTICLE (ARCTL_SURROGATE_KEY) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CSLIVE.STG_BRIDGE_ARTCTL_MNUFCTRE ADD CONSTRAINT FK_REFERENCE_25 FOREIGN KEY (MANFCTR_SURROGATE_KEY)
      REFERENCES CSLIVE.INCR_CS_STG_MANUFACTURERS (MANFCTR_SURROGATE_KEY) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CSLIVE.STG_BRIDGE_ARTCTL_REFRNCE ADD CONSTRAINT FK_REFERENCE_26 FOREIGN KEY (ARCTL_SURROGATE_KEY)
      REFERENCES CSLIVE.INCR_CS_STG_ARTICLE (ARCTL_SURROGATE_KEY) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CSLIVE.STG_BRIDGE_ARTCTL_REFRNCE ADD CONSTRAINT FK_REFERENCE_27 FOREIGN KEY (REF_SURROGATE_KEY)
      REFERENCES CSLIVE.INCR_CS_STG_REFERENCE (REF_SURROGATE_KEY) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CSLIVE.STG_BRIDGE_ATTRIBUTES ADD CONSTRAINT FK_REFERENCE_45 FOREIGN KEY (ATTR_SURROGATE_VALUE_KEY)
      REFERENCES INCR_CS_STG_ATTRIBUTE_VALUE (ATTR_SURROGATE_VALUE_KEY) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CSLIVE.STG_BRIDGE_ATTRIBUTES ADD CONSTRAINT FK_REFERENCE_46 FOREIGN KEY (ATTR_SURROGATE_KEY)
      REFERENCES CSLIVE.INCR_CS_STG_ATTRIBUTE (ATTR_SURROGATE_KEY) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CSLIVE.STG_BRIDGE_ENTITY ADD CONSTRAINT FK_REFERENCE_14 FOREIGN KEY (MANFCTR_SURROGATE_KEY)
      REFERENCES CSLIVE.INCR_CS_STG_MANUFACTURERS (MANFCTR_SURROGATE_KEY) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CSLIVE.STG_BRIDGE_ENTITY ADD CONSTRAINT FK_REFERENCE_16 FOREIGN KEY (REF_SURROGATE_KEY)
      REFERENCES CSLIVE.INCR_CS_STG_REFERENCE (REF_SURROGATE_KEY) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CSLIVE.STG_BRIDGE_ENTITY ADD CONSTRAINT FK_REFERENCE_19 FOREIGN KEY (ARCTL_SURROGATE_KEY)
      REFERENCES CSLIVE.INCR_CS_STG_ARTICLE (ARCTL_SURROGATE_KEY) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CSLIVE.STG_BRIDGE_ENTITY ADD CONSTRAINT FK_REFERENCE_28 FOREIGN KEY (ARTICLERELATION_ID)
      REFERENCES CSLIVE.INCR_CS_STG_ARTICLERELATION (ARTICLERELATION_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CSLIVE.STG_BRIDGE_ENTITY ADD CONSTRAINT FK_REFERENCE_44 FOREIGN KEY (COMPTBL_SURROGATE_KEY)
      REFERENCES CSLIVE.INCR_CS_STG_COMPATIBILITIES (COMPTBL_SURROGATE_KEY) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CSLIVE.STG_BRIDGE_MANFCTR_ATTRIBUTE ADD CONSTRAINT FK_REFERENCE_35 FOREIGN KEY (MANFCTR_SURROGATE_KEY)
      REFERENCES CSLIVE.INCR_CS_STG_MANUFACTURERS (MANFCTR_SURROGATE_KEY) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CSLIVE.STG_BRIDGE_MANFCTR_ATTRIBUTE ADD CONSTRAINT FK_REFERENCE_36 FOREIGN KEY (ATTR_STG_BRIDGE_KEY)
      REFERENCES CSLIVE.STG_BRIDGE_ATTRIBUTES (ATTR_STG_BRIDGE_KEY) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE STG_BRIDGE_MNUFCTRE_REFRNCE ADD CONSTRAINT FK_REFERENCE_20 FOREIGN KEY (MANFCTR_SURROGATE_KEY)
      REFERENCES CSLIVE.INCR_CS_STG_MANUFACTURERS (MANFCTR_SURROGATE_KEY) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE STG_BRIDGE_MNUFCTRE_REFRNCE ADD CONSTRAINT FK_REFERENCE_22 FOREIGN KEY (REF_SURROGATE_KEY)
      REFERENCES CSLIVE.INCR_CS_STG_REFERENCE (REF_SURROGATE_KEY) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CSLIVE.STG_BRIDGE_REFERENCE_ATTRIBUTE ADD CONSTRAINT FK_REFERENCE_37 FOREIGN KEY (REF_SURROGATE_KEY)
      REFERENCES CSLIVE.INCR_CS_STG_REFERENCE (REF_SURROGATE_KEY) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CSLIVE.STG_BRIDGE_REFERENCE_ATTRIBUTE ADD CONSTRAINT FK_REFERENCE_38 FOREIGN KEY (ATTR_STG_BRIDGE_KEY)
      REFERENCES CSLIVE.STG_BRIDGE_ATTRIBUTES (ATTR_STG_BRIDGE_KEY) ON DELETE RESTRICT ON UPDATE RESTRICT;
